### ISSUE TITLE
Out of date endpoints in data/boto-endpoints.json

### ISSUE THREAD

**Issue by Sp3000** [nccgroup/opinel#13]
I was trying to use Scout2 and was wondering why some of the newer regions weren't listed. It appears that boto-endpoints.json isn't quite up to date, and I had to update the list using http://docs.aws.amazon.com/general/latest/gr/rande.html

Just thought I'd give a heads up.

**Comment by l01cd3v** [comment]
I also removed the file in 8e80a9340d9a0e936b557ee2962ff1dd2dc40144.
Closing

**Comment by l01cd3v** [comment]
Getting the latest Scout2 code you'll get version 2.1.0 that should address this issue

**Comment by Sp3000** [comment]
Thanks! Seems to be working fine. Nice to see that it's back to automated.
