### ISSUE TITLE
Use MFA auth when mfa-code is provided

### ISSUE THREAD

**Issue by gforinger** [nccgroup/opinel#21]
Currently, If you specify an mfa-code on the Scout2 command line, it will be ignored without any warnings or errors.

In Scout2, `__main.py__` calls `read_creds` from `opinel/utils/credentials.py`

In `opinel/utils/credentials.py`, the `read_creds` function only does an `init_sts_session` with the mfa-code if the `force_init` bool is set to True, but that never happens if your `~/.aws/credentials` file doesn't contain a SessionToken already. If the session token doesn't exist, it should probably set `force_init` to True.

**Comment by l01cd3v** [comment]
Thanks !

**Comment by l01cd3v** [comment]
Should be fixed now - Only the first commit is relevant though...
